import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Bug, Clipboard, RefreshCw, Search, Trash2 } from "lucide-react";
import { Link } from "react-router-dom";
import PageHeader from "../../components/PageHeader.jsx";
import { useToast } from "../../components/Toast.jsx";
import { AttendanceApi } from "../../api.js";

export default function AppFeedback() {
  const [items,setItems]=useState([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true); const toast=useToast();
  async function load(){setLoading(true);try{const result=await AttendanceApi.getAppFeedback();setItems(result.data||[])}catch(error){toast.error(error.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>{const value=query.toLowerCase().trim();return value?items.filter(item=>[item.employeeName,item.employeeId,item.errorMessage,item.screen,item.actionAttempted].some(field=>String(field||"").toLowerCase().includes(value))):items},[items,query]);
  async function copy(item){const text=`Employee: ${item.employeeName} (${item.employeeId||"Not signed in"})\nPhone: ${item.phone||"-"}\nDate: ${new Date(item.occurredAt).toLocaleString()}\nScreen: ${item.screen}\nAction: ${item.actionAttempted}\nError: ${item.errorMessage}\nApp: ${item.appVersion||"-"}\nDevice: ${item.deviceModel||"-"}`;await navigator.clipboard.writeText(text);toast.success("Feedback copied.")}
  async function clearAll(){if(!items.length||!window.confirm(`Delete all ${items.length} previous feedback reports? This cannot be undone.`))return;try{const result=await AttendanceApi.deleteAllAppFeedback();toast.success(result.message);setItems([])}catch(error){toast.error(error.message)}}
  return <main className="screen feedbackPage"><div className="wide"><div className="adminHubTopbar"><PageHeader icon={Bug} title="Mobile App Feedback" subtitle="Investigate employee-reported app errors with complete occurrence context." tone="orange"/><Link className="btn dark" to="/admin"><ArrowLeft size={17}/> Admin Dashboard</Link></div><section className="feedbackStats"><article><b>{items.length}</b><span>Total reports</span></article><article><b>{new Set(items.map(x=>x.employeeId).filter(Boolean)).size}</b><span>Employees affected</span></article><article><b>{new Set(items.map(x=>x.screen)).size}</b><span>Screens affected</span></article></section><section className="feedbackToolbar panel"><div className="feedbackSearch"><Search size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search employee, screen, action or error..."/></div><button className="btn" onClick={load}><RefreshCw size={17}/> Refresh</button><button className="btn danger" disabled={!items.length} onClick={clearAll}><Trash2 size={17}/> Delete Previous Errors</button></section><section className="feedbackList">{loading?<div className="panel feedbackEmpty">Loading feedback reports...</div>:filtered.length?filtered.map(item=><article className="panel feedbackCard" key={item.id}><div className="feedbackCardHead"><div className="feedbackPerson"><span>{(item.employeeName||"U").slice(0,1).toUpperCase()}</span><div><b>{item.employeeName}</b><small>{item.employeeId||"Not signed in"}{item.phone?` · ${item.phone}`:""}</small></div></div><time>{new Date(item.occurredAt).toLocaleString()}</time></div><div className="feedbackContext"><span><small>WHERE IT OCCURRED</small><b>{item.screen}</b></span><span><small>WHAT USER TRIED</small><b>{item.actionAttempted}</b></span><span><small>APP / DEVICE</small><b>{item.appVersion||"-"} · {item.deviceModel||"-"}</b></span></div><div className="feedbackError"><small>ERROR MESSAGE</small><p>{item.errorMessage}</p></div><button className="feedbackCopy" onClick={()=>copy(item)}><Clipboard size={16}/> Copy Complete Report</button></article>):<div className="panel feedbackEmpty"><Bug size={38}/><b>No feedback reports found</b><span>Employee-submitted errors will appear here.</span></div>}</section></div></main>;
}
