import { useEffect, useState } from "react";
import { ArrowLeft, Eye, EyeOff, KeyRound, Save, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import PageHeader from "../../components/PageHeader.jsx";
import { AttendanceApi } from "../../api.js";
import { useToast } from "../../components/Toast.jsx";
const labels={admin:["Administrator","Full system and management access"],hr:["HR Manager","Employees, attendance and workforce access"],marketing:["Marketing Manager","Lead assignment and analysis access"],ceo:["Chief Executive Officer","Read-only attendance and employee visibility, plus alerts"]};
export default function DashboardCredentials(){
 const[accounts,setAccounts]=useState([]),[saving,setSaving]=useState(""),[visible,setVisible]=useState({});const toast=useToast();
 async function load(){try{const r=await AttendanceApi.getDashboardCredentials();if(!r.success)throw new Error(r.message);setAccounts((r.data||[]).map(x=>({...x,password:"",confirmPassword:""})))}catch(e){toast.error(e.message||"Could not load dashboard accounts.")}}
 useEffect(()=>{load()},[]);function change(role,key,value){setAccounts(c=>c.map(x=>x.role===role?{...x,[key]:value}:x))}
 async function save(a){if(a.password!==a.confirmPassword)return toast.warning("New password and confirmation do not match.");if(a.password&&a.password.length<8)return toast.warning("New password must contain at least 8 characters.");setSaving(a.role);try{const r=await AttendanceApi.updateDashboardCredential(a.role,a.username,a.password);if(!r.success)throw new Error(r.message);setAccounts(c=>c.map(x=>x.role===a.role?{...x,...r.data,password:"",confirmPassword:""}:x));toast.success(r.message)}catch(e){toast.error(e.message||"Credentials were not updated.")}finally{setSaving("")}}
 return <main className="screen credentialPage"><div className="wide"><div className="adminHubTopbar"><PageHeader icon={KeyRound} title="Dashboard Credentials" subtitle="Manage secure login IDs and passwords for every management portal." tone="purple"/><Link className="btn dark" to="/admin"><ArrowLeft size={17}/> Admin Dashboard</Link></div><div className="credentialNotice"><ShieldCheck size={22}/><div><b>Passwords are protected</b><span>Existing passwords are never displayed. Leave password fields empty to change only the login ID.</span></div></div><section className="credentialGrid">{accounts.map(a=><article className={`panel credentialCard ${a.role}`} key={a.role}><div className="credentialHeading"><span className="credentialRoleIcon"><KeyRound/></span><div><h2>{labels[a.role][0]}</h2><p>{labels[a.role][1]}</p></div></div><div className="field"><label>Login ID</label><input value={a.username} maxLength="50" onChange={e=>change(a.role,"username",e.target.value)} autoComplete="off"/></div><div className="field"><label>New Password</label><div className="passwordInput"><input type={visible[a.role]?"text":"password"} value={a.password} onChange={e=>change(a.role,"password",e.target.value)} placeholder="Minimum 8 characters" autoComplete="new-password"/><button type="button" onClick={()=>setVisible(c=>({...c,[a.role]:!c[a.role]}))}>{visible[a.role]?<EyeOff/>:<Eye/>}</button></div></div><div className="field"><label>Confirm Password</label><input type={visible[a.role]?"text":"password"} value={a.confirmPassword} onChange={e=>change(a.role,"confirmPassword",e.target.value)} placeholder="Repeat new password" autoComplete="new-password"/></div><button className="btn full" disabled={saving===a.role} onClick={()=>save(a)}><Save size={17}/>{saving===a.role?"Saving...":`Update ${labels[a.role][0]}`}</button>{a.updatedAt&&<small className="credentialUpdated">Last updated {new Date(a.updatedAt).toLocaleString()}</small>}</article>)}</section></div></main>;
}
