import { useEffect, useState } from "react";
import { Download, PackageCheck, Rocket, ShieldCheck, UploadCloud } from "lucide-react";
import PageHeader from "../../components/PageHeader.jsx";
import { useToast } from "../../components/Toast.jsx";

const config = window.ATTENDANCE_DB_CONFIG || {};
const apiKey = config.apiKey || localStorage.getItem("attendanceApiKey") || "";
function headers() { return apiKey ? { Authorization: `Bearer ${apiKey}` } : {}; }
function size(value) { const bytes=Number(value)||0; return bytes>1048576?`${(bytes/1048576).toFixed(1)} MB`:`${Math.ceil(bytes/1024)} KB`; }

export default function ReleaseManager() {
  const [latest,setLatest]=useState(null); const [file,setFile]=useState(null); const [versionCode,setVersionCode]=useState("");
  const [versionName,setVersionName]=useState(""); const [notes,setNotes]=useState(""); const [username,setUsername]=useState("admin");
  const [password,setPassword]=useState(""); const [progress,setProgress]=useState(0); const [publishing,setPublishing]=useState(false); const toast=useToast();
  async function load(){try{const response=await fetch("/api/app-update/latest",{headers:headers()});const data=await response.json();setLatest(data.available?data.release:null)}catch(error){toast.error(error.message)}}
  useEffect(()=>{load()},[]);
  async function downloadCurrent(){try{const response=await fetch("/api/app-update/download",{headers:headers()});if(!response.ok)throw new Error("Download failed.");const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`GlobalOne-${latest?.versionName||"latest"}.apk`;anchor.click();URL.revokeObjectURL(url)}catch(error){toast.error(error.message)}}
  function publish(event){event.preventDefault();if(!file)return toast.warning("Select the signed APK file.");const form=new FormData();form.append("apk",file);form.append("versionCode",versionCode);form.append("versionName",versionName);form.append("notes",notes);form.append("username",username);form.append("password",password);setPublishing(true);setProgress(0);const xhr=new XMLHttpRequest();xhr.open("POST","/api/app-update/publish");if(apiKey)xhr.setRequestHeader("Authorization",`Bearer ${apiKey}`);xhr.upload.onprogress=e=>e.lengthComputable&&setProgress(Math.round(e.loaded/e.total*100));xhr.onload=async()=>{setPublishing(false);let data={};try{data=JSON.parse(xhr.responseText)}catch{}if(xhr.status>=200&&xhr.status<300&&data.success){toast.success("Mandatory release published.");setPassword("");setFile(null);await load()}else toast.error(data.message||"Release failed.")};xhr.onerror=()=>{setPublishing(false);toast.error("Could not upload APK.")};xhr.send(form)}
  return <main className="screen"><div className="wide"><PageHeader icon={Rocket} title="Android Release Manager" subtitle="Publish signed APK updates directly to every employee app without Play Store." tone="cyan" />
    <section className="releaseGrid"><section className="panel releaseFormPanel"><div className="releasePanelHeading"><UploadCloud size={26}/><div><span className="eyebrow">NEW MANDATORY RELEASE</span><h2>Upload Android APK</h2></div></div><form onSubmit={publish}>
      <label className="apkDrop"><input type="file" accept=".apk,application/vnd.android.package-archive" onChange={e=>setFile(e.target.files?.[0]||null)}/><UploadCloud size={32}/><b>{file?file.name:"Choose signed APK"}</b><span>{file?size(file.size):"Maximum file size 200 MB"}</span></label>
      <div className="releaseFieldRow"><div className="field"><label>Version Code</label><input type="number" min="1" required value={versionCode} onChange={e=>setVersionCode(e.target.value)} placeholder="Example: 3"/></div><div className="field"><label>Version Name</label><input required value={versionName} onChange={e=>setVersionName(e.target.value)} placeholder="Example: 1.2.0"/></div></div>
      <div className="field"><label>Release Notes</label><textarea rows="5" maxLength="1000" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What changed in this version?"/></div>
      <div className="releaseSecurity"><ShieldCheck size={20}/><div><b>Confirm admin credentials</b><span>Required for every APK publication.</span></div></div><div className="releaseFieldRow"><div className="field"><label>Admin ID</label><input required value={username} onChange={e=>setUsername(e.target.value)}/></div><div className="field"><label>Admin Password</label><input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></div></div>
      {publishing&&<div className="uploadProgress"><div style={{width:`${progress}%`}}/><span>{progress}% uploaded</span></div>}<button className="btn full cyan" disabled={publishing}>{publishing?"Publishing...":"Publish Mandatory Update"}</button>
    </form></section>
    <aside className="panel latestRelease"><div className="releasePanelHeading"><PackageCheck size={26}/><div><span className="eyebrow">CURRENT RELEASE</span><h2>Latest published APK</h2></div></div>{latest?<><div className="versionHero"><b>v{latest.versionName}</b><span>Build {latest.versionCode}</span></div><dl><div><dt>Released</dt><dd>{new Date(latest.releasedAt).toLocaleString()}</dd></div><div><dt>APK size</dt><dd>{size(latest.sizeBytes)}</dd></div><div><dt>Policy</dt><dd><span className="mandatoryBadge">Mandatory</span></dd></div><div><dt>SHA-256</dt><dd className="checksum">{latest.sha256}</dd></div></dl><div className="releaseNotes"><b>Release notes</b><p>{latest.notes||"No release notes."}</p></div><button className="btn full" onClick={downloadCurrent}><Download size={17}/> Download current APK</button></>:<div className="releaseEmpty"><PackageCheck size={40}/><b>No APK published</b><span>Upload the first mandatory employee-app release.</span></div>}</aside></section>
    <div className="releaseWarning"><ShieldCheck size={20}/><p><b>Signing requirement:</b> Every uploaded APK must use the same Android signing key as the installed app. Android will reject differently signed packages.</p></div>
  </div></main>
}
